/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahen
 */
public class PanelMenuBarang extends javax.swing.JFrame {

    /**
     * Creates new form PanelMenuMurid
     */
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    String nama_murid = MuridSession.getM_nama_murid();
    
    public void tampilComboBox(){
        
        
        try {
           String sql ="SELECT *FROM barang";
           stat=con.createStatement();
           rs=stat.executeQuery(sql);
           while (rs.next())
           {
             String barang=rs.getString("nama_barang");         
             pilih.addItem(barang);
            
           }
           rs.close();
           con.close();
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "GAGAL MENAMPILKAN DATA");
        }
    }
    
    public void tampilKodePembelian(){
        try {
            koneksi DB = new koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            sql="SELECT * FROM pembelian ORDER BY kode_pembelian DESC";
            stat=con.createStatement();
            rs=stat.executeQuery(sql);
            if (rs.next()) {
                String nofak = rs.getString("kode_pembelian").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}

               txt_kode_pembelian.setText("P" + Nol + AN);
            } else {
               txt_kode_pembelian.setText("P0001");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
    }
    
           
    
    public PanelMenuBarang(){
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
        nama_pembeli.setText(nama_murid);
        
        tampilComboBox();
        tampilKodePembelian();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pilih = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        max = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        BayarFinal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        masuk = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        txt_kode_pembelian = new javax.swing.JTextField();
        txt_kode_barang = new javax.swing.JTextField();
        nama_pembeli = new javax.swing.JTextField();
        sisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 87, 101));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton1.setText("Batal");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, null, null));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 377, 94, 37));

        pilih.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daftar Barang" }));
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });
        pilih.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pilihKeyReleased(evt);
            }
        });
        jPanel2.add(pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 105, 190, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel1.setText("Pilih Barang");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 105, -1, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel2.setText("Harga Satuan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel3.setText("Jumlah");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel4.setText("Total");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        harga.setEditable(false);
        jPanel2.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 154, 190, -1));

        max.setEditable(false);
        jPanel2.add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 70, 30));

        total.setEditable(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 190, -1));

        BayarFinal.setBackground(new java.awt.Color(0, 204, 0));
        BayarFinal.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        BayarFinal.setText("Bayar");
        BayarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarFinalActionPerformed(evt);
            }
        });
        jPanel2.add(BayarFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 377, 82, 37));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("Tunai");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });
        jPanel2.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 190, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel7.setText("Form Pembelian Barang");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel8.setText("Max");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        jumlah.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jumlahInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });
        jPanel2.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 70, 30));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 270, 240));

        masuk.setBackground(new java.awt.Color(102, 102, 255));
        masuk.setForeground(new java.awt.Color(102, 102, 255));
        masuk.setText("jTextField1");
        masuk.setBorder(null);
        masuk.setOpaque(false);
        jPanel2.add(masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        kembalian.setEditable(false);
        kembalian.setBackground(new java.awt.Color(102, 102, 255));
        kembalian.setForeground(new java.awt.Color(102, 102, 255));
        kembalian.setBorder(null);
        kembalian.setOpaque(false);
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        jPanel2.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 70, -1));

        txt_kode_pembelian.setEditable(false);
        txt_kode_pembelian.setBackground(new java.awt.Color(102, 102, 255));
        txt_kode_pembelian.setForeground(new java.awt.Color(102, 102, 255));
        txt_kode_pembelian.setBorder(null);
        txt_kode_pembelian.setOpaque(false);
        jPanel2.add(txt_kode_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 70, -1));

        txt_kode_barang.setEditable(false);
        txt_kode_barang.setBackground(new java.awt.Color(102, 102, 255));
        txt_kode_barang.setForeground(new java.awt.Color(102, 102, 255));
        txt_kode_barang.setBorder(null);
        txt_kode_barang.setOpaque(false);
        jPanel2.add(txt_kode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 70, -1));

        nama_pembeli.setEditable(false);
        nama_pembeli.setBackground(new java.awt.Color(102, 102, 255));
        nama_pembeli.setForeground(new java.awt.Color(102, 102, 255));
        nama_pembeli.setBorder(null);
        nama_pembeli.setOpaque(false);
        jPanel2.add(nama_pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 70, -1));

        sisa.setEditable(false);
        sisa.setBackground(new java.awt.Color(102, 102, 255));
        sisa.setForeground(new java.awt.Color(102, 102, 255));
        sisa.setBorder(null);
        sisa.setOpaque(false);
        jPanel2.add(sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_totalActionPerformed

    private void pilihKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pilihKeyReleased
        // TODO add your handling code here:
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        try
        {
           String sql ="SELECT *FROM barang where nama_barang='"+pilih.getSelectedItem()+"'";
           stat=con.createStatement();
           rs=stat.executeQuery(sql);
           while (rs.next())
           {
             harga.setText(rs.getString("Harga"));
             max.setText(rs.getString("jumlah_barang"));
             masuk.setText(rs.getString("kode_barang"));

           }
           rs.close();
           con.close();
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "GAGAL MENAMPILKAN DATA Harga");
        }
    }//GEN-LAST:event_pilihKeyReleased

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        // TODO add your handling code here:
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        try
        {
           String sql ="SELECT *FROM barang where nama_barang='"+pilih.getSelectedItem()+"'";
           stat=con.createStatement();
           rs=stat.executeQuery(sql);
           while (rs.next())
           {
             harga.setText(rs.getString("Harga"));
             max.setText(rs.getString("jumlah_barang"));
             txt_kode_barang.setText(rs.getString("kode_barang"));

           }
           rs.close();
           con.close();
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "GAGAL MENAMPILKAN DATA Harga");
        }
        
    }//GEN-LAST:event_pilihActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
        harga.getText();
        int x = Integer.parseInt(max.getText());
        

        String y = jumlah.getText();
        int a = Integer.parseInt(y);
        
        if(a > x){
            JOptionPane.showMessageDialog(null, a);
            
        }
        
    }//GEN-LAST:event_jumlahActionPerformed

    private void jumlahInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jumlahInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumlahInputMethodTextChanged

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        // TODO add your handling code here:
        
        harga.getText();
        int x = Integer.parseInt(max.getText());

        String y = jumlah.getText();
        int a = Integer.parseInt(y);
        String t = max.getText();
        int u = Integer.parseInt(t);
        
        int q = u-a;
        String d = Integer.toString(q);
        sisa.setText(d);
        
        String l = harga.getText();
        int k = Integer.parseInt(l);
        
        int s = a * k;
        String m = Integer.toString(s);
        total.setText(m);
    }//GEN-LAST:event_jumlahKeyReleased

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        // TODO add your handling code here:
        String a = bayar.getText();
        int b = Integer.parseInt(a);
        
        String c = total.getText();
        int d = Integer.parseInt(c);
        int k = b-d;
        String s = String.valueOf(k);
        kembalian.setText(s);
    }//GEN-LAST:event_bayarKeyReleased

    private void BayarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarFinalActionPerformed
        // TODO add your handling code here:
        
        String a = bayar.getText();
        int b = Integer.parseInt(a);
        String c = total.getText();
        int d = Integer.parseInt(c);
        harga.getText();
        int x = Integer.parseInt(max.getText());
        String y = jumlah.getText();
        int p = Integer.parseInt(y);
        
        if(p > x){
            JOptionPane.showMessageDialog(null, "Jumlah Maksimal tidak boleh lebih dari "+x);
        }
        
        else if(b < d){
            JOptionPane.showMessageDialog(null, "Uang anda kurang !");
        }else{
        int k = b - d;
        txtArea.setText("                           APLIKASI KOPSIS\n"+
                "                      SMKN 2 TRENGGALEK \n"+
                "        Jl. Ronggowarsito Gg. Sidomukti No.1\n"+ 
                "\n"+
                "    Nama                   :   "+pilih.getSelectedItem()+"\n"+
                "\tx "+jumlah.getText()+"\n"+
                "-------------------------------------------------\n"+        
                "    Total                      :   Rp."+total.getText()+"\n"+
                "-------------------------------------------------\n"+
                "    Tunai                     :   Rp."+bayar.getText()+"\n"+
                "    Kembali                :   Rp."+k+"\n"+
                "\n"+
                "            Terimakasih Sudah Berbelanja");
        
        
        //----------------------------INSERT DATABASE PEMBELIAN ----------------------------
        try {
            koneksi DB = new koneksi();
            DB.config();
            con = DB.con;
            stat = DB.stm;
            stat = con.createStatement();
            stat.executeUpdate("INSERT INTO pembelian VALUES('"+ txt_kode_pembelian.getText() + "','"
                + txt_kode_barang.getText() + "','"
                + nama_pembeli.getText() + "','"
                + jumlah.getText() + "','"
                + total.getText() + "','"
                + bayar.getText() + "','"
                + kembalian.getText() +"')");
            
            stat.executeUpdate("UPDATE barang SET "
                + "kode_barang='"      + txt_kode_barang.getText() + "', "
                        
                + "jumlah_barang='"    + sisa.getText() +  "'"
                + "WHERE kode_barang='"    + txt_kode_barang.getText() +"'");
            
            JOptionPane.showMessageDialog(null, "Pembelian Berhasil");
            try {
            sql="SELECT * FROM pembelian ORDER BY kode_pembelian DESC";
            stat=con.createStatement();
            rs=stat.executeQuery(sql);
            if (rs.next()) {
                String nofak = rs.getString("kode_pembelian").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}

               txt_kode_pembelian.setText("P" + Nol + AN);
            } else {
               txt_kode_pembelian.setText("P0001");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
            txt_kode_barang.setText("");
            masuk.setText("");
            jumlah.setText("");
            total.setText("");
            bayar.setText("");
            kembalian.setText("");
          } catch (Exception e) {
            e.printStackTrace();
          }

        }
         
    }//GEN-LAST:event_BayarFinalActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMenuBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMenuBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMenuBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMenuBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMenuBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BayarFinal;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField masuk;
    private javax.swing.JTextField max;
    private javax.swing.JTextField nama_pembeli;
    public javax.swing.JComboBox<String> pilih;
    private javax.swing.JTextField sisa;
    private javax.swing.JTextField total;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txt_kode_barang;
    private javax.swing.JTextField txt_kode_pembelian;
    // End of variables declaration//GEN-END:variables
}
